#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weather.Android.Resource", IsApplication=true)]

namespace Weather.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int red_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int WeatherStatus200d = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int WeatherStatus200n = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int WeatherStatus201d = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int WeatherStatus201n = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int WeatherStatus202d = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int WeatherStatus202n = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int WeatherStatus210d = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int WeatherStatus210n = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int WeatherStatus211d = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int WeatherStatus211n = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int WeatherStatus212d = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int WeatherStatus212n = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int WeatherStatus221d = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int WeatherStatus221n = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int WeatherStatus230d = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int WeatherStatus230n = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int WeatherStatus231d = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int WeatherStatus231n = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int WeatherStatus232d = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int WeatherStatus232n = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int WeatherStatus300d = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int WeatherStatus300n = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int WeatherStatus301d = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int WeatherStatus301n = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int WeatherStatus302d = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int WeatherStatus302n = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int WeatherStatus310d = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int WeatherStatus310n = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int WeatherStatus311d = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int WeatherStatus311n = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int WeatherStatus312d = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int WeatherStatus312n = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int WeatherStatus321d = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int WeatherStatus321n = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int WeatherStatus500d = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int WeatherStatus500n = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int WeatherStatus501d = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int WeatherStatus501n = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int WeatherStatus502d = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int WeatherStatus502n = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int WeatherStatus503d = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int WeatherStatus503n = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int WeatherStatus504d = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int WeatherStatus504n = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int WeatherStatus511d = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int WeatherStatus511n = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int WeatherStatus520d = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int WeatherStatus520n = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int WeatherStatus521d = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int WeatherStatus521n = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int WeatherStatus522d = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int WeatherStatus522n = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int WeatherStatus600d = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int WeatherStatus600n = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int WeatherStatus601d = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int WeatherStatus601n = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int WeatherStatus602d = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int WeatherStatus602n = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int WeatherStatus611d = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int WeatherStatus611n = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int WeatherStatus621d = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int WeatherStatus621n = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int WeatherStatus701d = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int WeatherStatus701n = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int WeatherStatus711d = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int WeatherStatus711n = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int WeatherStatus721d = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int WeatherStatus721n = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int WeatherStatus731d = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int WeatherStatus731n = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int WeatherStatus741d = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int WeatherStatus741n = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int WeatherStatus800d = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int WeatherStatus800n = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int WeatherStatus801d = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int WeatherStatus801n = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int WeatherStatus802d = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int WeatherStatus802n = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int WeatherStatus803d = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int WeatherStatus803n = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int WeatherStatus804d = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int WeatherStatus804n = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int WeatherStatus900d = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int WeatherStatus900n = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int WeatherStatus901d = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int WeatherStatus901n = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int WeatherStatus902d = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int WeatherStatus902n = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int WeatherStatus903d = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int WeatherStatus903n = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int WeatherStatus904d = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int WeatherStatus904n = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int WeatherStatus905d = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int WeatherStatus905n = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int WeatherStatus906d = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int WeatherStatus906n = 2130837601;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int MyButton = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int editTextCity = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int horizontalScrollHourlyForecast = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int imageViewCurrentWeather = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int imageViewForecastImage = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayoutHourlyForecast = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int linearLayoutWeather = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int progressBarLoading = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int textViewCity = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textViewCurrentTemp = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textViewDescription = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int textViewTempRange = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HourlyForecast = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int base_text_block_style = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int button_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int caption_text_block_style = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int header_text_style = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int sub_header_text_style = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int sub_title_text_style = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int title_text_style = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
